<h1><?php echo $this->getHelloWorldTxt(); ?></h1>

<h1>Magento jQuery widgets</h1>

<h2> 1. Accordion widget </h2>

<h4>Example of magento stackexchange </h4>
<div class="block filter" id="layered-filter-block">
    <div class="block-content filter-content">
        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": true, "multipleCollapsible": true}}'>
            <div data-role="collapsible" class="filter-options-item" >
                <div data-role="title" class="filter-options-title">Title 1</div>
                <div data-role="content" class="filter-options-content">content 1</div>
            </div>
            <div data-role="collapsible" class="filter-options-item" >
                <div data-role="title" class="filter-options-title">Title 2</div>
                <div data-role="content" class="filter-options-content">content 2</div>
            </div>
            <div data-role="collapsible" class="filter-options-item" >
                <div data-role="title" class="filter-options-title">Title 3</div>
                <div data-role="content" class="filter-options-content">content 3</div>
            </div>
        </div>
    </div>
</div>

<script>
    require([
            'jquery',
            'accordion'
        ],
        function($){
            'use strict';
            $( document ).ready(function() {
                $( "#narrow-by-list" ).accordion({
                    "openedState": "active",
                    "collapsible": true,
                    "active": [1,4], /** Integrat Dynamic open tab  */
                    "multipleCollapsible": true
                });
            });
        });
</script>

<h2> 2. Alert widget </h2>
<div class="alert-element">
    <a id="alert-element">
        This is an alert widget
    </a>
</div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function($,alert) { // Variable that represents the `alert` function

        $("#alert-element").click(function(){
            alert({
                title: 'Some title',
                content: 'Some content',
                actions: {
                    always: function(){}
                }
            });
        });
    });
</script>

<h2> 3. Calendar widget </h2>
<h4>Example 01</h4>
<div class="field overview required" data-role="filter-form" id="date_range">
     <span class="field-row">
         <label for="date_from">
             <span><?php echo __('From') ?>:</span>
         </label>
         <input class="input-text required-entry"
                type="text"
                id="date_from"
                name="from"
         />
           <span id="date_from_advice"></span>
       </span>

       <span class="field-row">
             <label for="date_to">
                 <span><?php echo __('To') ?>:</span>
             </label>
             <input class="input-text required-entry"
                    type="text"
                    id="date_to"
                    name="report_to"
             />
             <span id="date_to_advice"></span>
        </span>
    <script>
        require([
            "jquery",
            "mage/calendar"
        ], function($){
            $("#date_range").dateRange({
                buttonText:"<?php echo __('Select Date') ?>",
                from:{
                    id:"date_from"
                },
                to:{
                    id:"date_to"
                }
            });
        });
    </script>
</div>
<!----------------------------------------------------------------------------------------------->
<h4>Example 02</h4>
<input type="text" class="input-text required-entry" id="txtcalendar" name="txtcalendar" aria-required="true" >

<script>
    require([
        "jquery",
        "mage/calendar"
    ], function($){
        $("#txtcalendar").calendar({
            buttonText:"<?php echo __('Select Date') ?>",
        });
    });
</script>
<!----------------------------------------------------------------------------------------------->

<h2> 4. Collapsible widget </h2>

<p id="collap-element">collapsible</p>
<p></p>
<script>
    require([
        "jquery",
        "mage/collapsible"
    ], function($){
        $("#collap-element").collapsible();
    });
</script>
<!----------------------------------------------------------------------------------------------->

<h2>5. Confirmation widget </h2>
<div class="confirm-element">
    <a id="confirm-element">
        This is an confirm widget
    </a>
</div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function($,confirmation) {

        $('#confirm-element').click(function(){
            confirmation({
                title: 'Some title',
                content: 'Some content',
                actions: {
                    confirm: function(){},
                    cancel: function(){},
                    always: function(){}
                }
            });
        });
    });
</script>

<!----------------------------------------------------------------------------------------------->

<h2>6. Dropdown Dialog widget</h2>
<div class="example-dropdown-2" data-mage-init='{"dropdown":{}}'>
    <span class="action toggle" data-toggle="dropdown" aria-haspopup="true">
            <span>span + dropdown</span>
    </span>
    <ul class="dropdown">
        <li>
            <span class="item">One</span>
        </li>
        <li>
            <span class="item">Two</span>
        </li>
        <li>
            <span class="item">Three</span>
        </li>
    </ul>
</div>
<script>

</script>
<!----------------------------------------------------------------------------------------------->

<h2>7. Gallery Widget</h2>

<h2>8. List Widget</h2>

<h2>9. Magnifier Widget</h2>

<!----------------------------------------------------------------------------------------------->
<h2>10. Loader Widget</h2>

<div data-role="pannel" data-mage-init='{"loader":{}}'>
    <span id="loader-span">content</span>
</div>
<script>
    require([
        'jquery',
        'mage/loader'
    ], function($) {

        $('#loader-span').click(function(){
            $('[data-role="pannel"]').trigger('show.loader');
        });
    });
</script>
<!----------------------------------------------------------------------------------------------->

<h2>11. Menu Widget</h2>

<!----------------------------------------------------------------------------------------------->
<h2>12. Modal Widget</h2>
<h4>On click modal widget</h4>
<div>
    <a href="" id="click-this">Click this</a>
</div>
<div id="popup-modal" style="display: none;">
    <h2> hello .... </h2>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
                buttons: [{
                    text: 'Continue',
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#click-this").on('click',function(){
                $("#popup-modal").modal("openModal");
            });
        });
</script>

<!----------------------------------------------------------------------------------------------->